//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekzamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car2
    {
        public int Id_Car { get; set; }
        public string Name_Car2 { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
