//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekzamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovors
    {
        public string Strah_summ { get; set; }
        public int Srock { get; set; }
        public int Id_Object { get; set; }
        public int Id_Client { get; set; }
        public int id_Dogovor { get; set; }
        public string Strah_Plateseh { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Object Object { get; set; }
    }
}
