//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekzamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int Id_Review { get; set; }
        public string Text { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
